packages:
  - examples/browser

allowBuilds:
  esbuild: false
  simple-git-hooks: true

minimumReleaseAge: 0
shellEmulator: true
trustLockfile: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080 # 7 days
